version: '3.1'

services:

  bugatti-api:
    build:
      context: .
    image: tgalske/bugatti-api
    restart: always
    networks:
      - bugatti-net
    ports:
      - "3000:3000"

networks:
  bugatti-net:
    external: true
